

-- Questions for family-friends
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends '),
( 'How has a friend influenced a major life decision you''ve made? ',  'questions ',  'family-friends '),
( 'What''s the most memorable family vacation you''ve been on? ',  'questions ',  'family-friends '),
( 'Who''s the family member you turn to for advice, and why? ',  'questions ',  'family-friends '),
( 'What''s a funny story about a family gathering that still makes you laugh? ',  'questions ',  'family-friends '),
( 'How do you stay connected with friends who live far away? ',  'questions ',  'family-friends '),
( 'What''s a lesson about friendship you learned the hard way? ',  'questions ',  'family-friends '),
( 'What''s a small gesture from a family member that made a big impact on you? ',  'questions ',  'family-friends '),
( 'How do you handle disagreements with close friends? ',  'questions ',  'family-friends '),
( 'What''s a childhood memory with a sibling or cousin that shaped who you are? ',  'questions ',  'family-friends '),
( 'What''s a family tradition that means a lot to you and why? ',  'questions ',  'family-friends ');

-- Questions for dating-relationship
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship '),
( 'How do you know when you''ve found ''the one''? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship lesson you wish you learned earlier? ',  'questions ',  'dating-relationship '),
( 'What''s the most important quality you look for in a partner? ',  'questions ',  'dating-relationship '),
( 'How do you keep the spark alive in a long-term relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a memorable first date story you have? ',  'questions ',  'dating-relationship '),
( 'How do you handle differences in communication styles with a partner? ',  'questions ',  'dating-relationship '),
( 'What''s something small your partner does that makes you feel loved? ',  'questions ',  'dating-relationship '),
( 'How do you balance personal space and togetherness in a relationship? ',  'questions ',  'dating-relationship '),
( 'What''s a relationship goal you''re currently working toward? ',  'questions ',  'dating-relationship '),
( 'What''s the most romantic gesture you''ve ever made or received? ',  'questions ',  'dating-relationship ');

-- Questions for fiction
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction '),
( 'What''s a fictional character you relate to deeply, and why? ',  'questions ',  'fiction '),
( 'If you could have any superpower, what would it be and how would you use it? ',  'questions ',  'fiction '),
( 'What''s a book or movie plot twist that still amazes you? ',  'questions ',  'fiction '),
( 'If you could write a sequel to any story, which one would it be? ',  'questions ',  'fiction '),
( 'What''s a fictional friendship or relationship you admire? ',  'questions ',  'fiction '),
( 'If you could be any mythical creature, what would you choose? ',  'questions ',  'fiction '),
( 'What''s a fictional setting you''d love to explore in real life? ',  'questions ',  'fiction '),
( 'If you could meet any author or creator, who would it be and what would you ask? ',  'questions ',  'fiction '),
( 'What''s a story that changed the way you see the world? ',  'questions ',  'fiction '),
( 'If you could live in any fictional world, where would it be and why? ',  'questions ',  'fiction ');

-- Questions for only-wrong-answers
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers '),
( 'What''s a hilarious mistake you made that turned out okay? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most ridiculous thing you''ve believed to be true? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny misunderstanding you''ve had with someone? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst gift you''ve ever given or received? ',  'questions ',  'only-wrong-answers '),
( 'What''s a silly rule you had to follow as a kid? ',  'questions ',  'only-wrong-answers '),
( 'What''s the most absurd trend or fad you participated in? ',  'questions ',  'only-wrong-answers '),
( 'What''s a comical failure you''ve had in the kitchen? ',  'questions ',  'only-wrong-answers '),
( 'What''s the weirdest thing you''ve done just to see what would happen? ',  'questions ',  'only-wrong-answers '),
( 'What''s a funny ''wrong answer'' you''ve given on purpose? ',  'questions ',  'only-wrong-answers '),
( 'What''s the worst advice you''ve ever received, and did you follow it? ',  'questions ',  'only-wrong-answers ');

-- Questions for travel
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel '),
( 'If you could travel anywhere in the world, where would you go? ',  'questions ',  'travel '),
( 'What''s a travel experience that changed your perspective? ',  'questions ',  'travel '),
( 'What''s the best food you''ve tried while traveling? ',  'questions ',  'travel '),
( 'What''s a travel mishap that turned into a great story? ',  'questions ',  'travel '),
( 'What''s a cultural tradition you discovered while traveling? ',  'questions ',  'travel '),
( 'What''s the most beautiful natural wonder you''ve seen in person? ',  'questions ',  'travel '),
( 'What''s a travel destination on your bucket list, and why? ',  'questions ',  'travel '),
( 'What''s a memorable interaction you had with a local while traveling? ',  'questions ',  'travel '),
( 'What''s the most adventurous thing you''ve done on a trip? ',  'questions ',  'travel '),
( 'What''s the most unforgettable place you''ve traveled to, and why? ',  'questions ',  'travel ');

-- Questions for money
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money '),
( 'What''s a money-saving tip that has worked well for you? ',  'questions ',  'money '),
( 'What''s the most valuable thing you''ve ever bought, and why? ',  'questions ',  'money '),
( 'How do you decide when to splurge on something expensive? ',  'questions ',  'money '),
( 'What''s a financial goal you''re working toward right now? ',  'questions ',  'money '),
( 'What''s the most important lesson you''ve learned about money? ',  'questions ',  'money '),
( 'What''s a creative way you''ve earned extra cash? ',  'questions ',  'money '),
( 'How do you budget for things you love without overspending? ',  'questions ',  'money '),
( 'What''s a purchase you regretted, and what did you learn from it? ',  'questions ',  'money '),
( 'What''s something you''d spend a lot of money on if you could afford it? ',  'questions ',  'money '),
( 'What''s the best financial advice you''ve ever received? ',  'questions ',  'money ');

-- Questions for 18+
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ '),
( 'How do you communicate your needs in a relationship? ',  'questions ',  '18+ '),
( 'What''s a romantic fantasy you''ve always wanted to explore? ',  'questions ',  '18+ '),
( 'What''s the most important aspect of physical connection for you? ',  'questions ',  '18+ '),
( 'How do you keep passion alive in a long-term relationship? ',  'questions ',  '18+ '),
( 'What''s a personal boundary you set in intimate relationships? ',  'questions ',  '18+ '),
( 'What''s something you''ve discovered about your own desires? ',  'questions ',  '18+ '),
( 'How do you handle differences in preferences with a partner? ',  'questions ',  '18+ '),
( 'What''s a memorable moment of connection you''ve shared with someone? ',  'questions ',  '18+ '),
( 'What''s a relationship topic you wish people discussed more openly? ',  'questions ',  '18+ '),
( 'What''s something you''ve learned about intimacy over the years? ',  'questions ',  '18+ ');

-- Questions for randomized
-- SQL script to insert questions into Supabase content table
INSERT INTO content (content, type, category) VALUES
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized '),
( 'If you could have any talent instantly, what would you choose? ',  'questions ',  'randomized '),
( 'What''s a hobby you''ve always wanted to try, and why? ',  'questions ',  'randomized '),
( 'What''s the most spontaneous thing you''ve ever done? ',  'questions ',  'randomized '),
( 'What''s a random act of kindness that made your day? ',  'questions ',  'randomized '),
( 'If you could switch lives with someone for a day, who would it be? ',  'questions ',  'randomized '),
( 'What''s a quirky habit or interest you have that surprises people? ',  'questions ',  'randomized '),
( 'What''s the weirdest food combination you enjoy? ',  'questions ',  'randomized '),
( 'What''s a random memory from your past that still makes you smile? ',  'questions ',  'randomized '),
( 'If you could time travel, would you go to the past or future, and why? ',  'questions ',  'randomized '),
( 'What''s the most unexpected thing you''ve learned about yourself? ',  'questions ',  'randomized ');