-- SQL script to add 100 more content items (questions, situations, dilemmas) per category
-- Total of 300 content items per category after previous insertions
-- Disable RLS temporarily for insertion
ALTER TABLE content DISABLE ROW LEVEL SECURITY;

-- Family-Friends Category (100 additional)
INSERT INTO content (content, type, category) VALUES
('What''s the most valuable life lesson a family member taught you through their actions?', 'questions', 'family-friends'),
('Imagine you''re organizing a surprise reunion for a family member who hasn''t seen everyone in years. How do you make it unforgettable?', 'situations', 'family-friends'),
('Would you rather spend a year traveling with your best friend or your closest family member, and why?', 'dilemmas', 'family-friends'),
('How do you rebuild trust with a friend after a major misunderstanding?', 'questions', 'family-friends'),
('You notice a friend seems withdrawn at a gathering. Do you approach them privately or give them space?', 'situations', 'family-friends'),
('Is it more important to have a small circle of very close friends or a large network of acquaintances?', 'dilemmas', 'family-friends'),
('What''s a family memory that shaped your understanding of love or sacrifice?', 'questions', 'family-friends'),
('Your sibling is going through a tough breakup. How do you support them without overstepping?', 'situations', 'family-friends'),
('Would you forgive a friend who shared a personal secret of yours, even if unintentionally?', 'dilemmas', 'family-friends'),
('How has a friendship challenged you to grow in ways you didn''t expect?', 'questions', 'family-friends'),
('You''re planning a family game night, but not everyone gets along. How do you ensure it''s still fun for all?', 'situations', 'family-friends'),
('Is it better to confront family issues head-on or let small conflicts resolve themselves over time?', 'dilemmas', 'family-friends'),
('What''s a moment with a friend that made you realize the true meaning of loyalty?', 'questions', 'family-friends'),
('Your cousin asks for a large loan you can afford but aren''t sure they''ll repay. How do you handle it?', 'situations', 'family-friends'),
('Would you rather have a friend who always tells the brutal truth or one who softens it to spare your feelings?', 'dilemmas', 'family-friends'),
('How do you honor a family member''s legacy in your daily life?', 'questions', 'family-friends'),
('You accidentally overhear a friend talking negatively about you. Do you confront them or let it go?', 'situations', 'family-friends'),
('Is family history more about shared blood or shared experiences?', 'dilemmas', 'family-friends'),
('What''s a time a friend stood by you during your lowest point, and how did it impact you?', 'questions', 'family-friends'),
('Your family is split on where to spend the holidays. How do you help find a solution everyone accepts?', 'situations', 'family-friends'),
('Would you risk a friendship by giving honest feedback they might not want to hear?', 'dilemmas', 'family-friends'),
('How do you maintain closeness with family members who have very different beliefs or lifestyles?', 'questions', 'family-friends'),
('A close friend asks you to keep a secret that makes you uncomfortable. What do you do?', 'situations', 'family-friends'),
('Is it more important for family to support your dreams or keep you grounded?', 'dilemmas', 'family-friends'),
('What''s a family tradition that connects you to your roots, and why does it matter to you?', 'questions', 'family-friends'),
('You''re tasked with planning a friend''s milestone birthday, but they''re hard to please. How do you approach it?', 'situations', 'family-friends'),
('Would you choose to live closer to family if it meant giving up a dream job opportunity?', 'dilemmas', 'family-friends'),
('How do you help a friend who''s struggling with self-doubt without sounding patronizing?', 'questions', 'family-friends'),
('Your family discovers a long-lost relative who wants to reconnect. How do you welcome them?', 'situations', 'family-friends'),
('Is it better to have friends who challenge your views or those who always agree with you?', 'dilemmas', 'family-friends'),
('What''s a piece of advice from a family member that you live by every day?', 'questions', 'family-friends'),
('A friend cancels plans last minute repeatedly. Do you address it or let it slide again?', 'situations', 'family-friends'),
('Would you rather spend more time with family now or save that time for later in life?', 'dilemmas', 'family-friends'),
('How has a friend''s perspective helped you see a personal flaw you needed to work on?', 'questions', 'family-friends'),
('You''re hosting a family event, but a relative often causes drama. How do you prepare?', 'situations', 'family-friends'),
('Is it more important to be completely honest with family or protect their feelings sometimes?', 'dilemmas', 'family-friends'),
('What''s a shared family struggle that brought everyone closer together?', 'questions', 'family-friends'),
('Your best friend is moving far away. How do you make the most of your remaining time together?', 'situations', 'family-friends'),
('Would you rather have a family that''s overly involved or one that gives you complete independence?', 'dilemmas', 'family-friends'),
('How do you show a friend they''re valued beyond just words?', 'questions', 'family-friends'),
('A family member criticizes your life choices at a gathering. How do you respond without escalating tension?', 'situations', 'family-friends'),
('Is it harder to forgive a family member or a close friend for a major betrayal?', 'dilemmas', 'family-friends'),
('What''s a family story that inspires you to overcome challenges?', 'questions', 'family-friends'),
('You notice a friend drifting away after a life change. How do you attempt to reconnect?', 'situations', 'family-friends'),
('Would you prioritize a family obligation over a once-in-a-lifetime event with friends?', 'dilemmas', 'family-friends'),
('How do you balance supporting a family member''s dreams while being realistic about their chances?', 'questions', 'family-friends'),
('Your family is planning a big celebration, but budgets are tight. How do you make it special without overspending?', 'situations', 'family-friends'),
('Is it more meaningful to have friends from childhood or those you meet later in life?', 'dilemmas', 'family-friends'),
('What''s a time a family member''s resilience amazed you, and how did it influence your own strength?', 'questions', 'family-friends'),
('A friend asks for help moving, but you''re swamped with work. Do you make time or explain your situation?', 'situations', 'family-friends'),
('Would you rather have a family that openly expresses emotions or one that keeps feelings private?', 'dilemmas', 'family-friends'),
('How do you celebrate a friend''s success when you''re struggling with your own challenges?', 'questions', 'family-friends'),
('You find an old family album full of forgotten memories. How do you share this discovery with others?', 'situations', 'family-friends'),
('Is it more important to maintain peace in family dynamics or address every issue that arises?', 'dilemmas', 'family-friends'),
('What''s a gesture of friendship that left a lasting impact on your life?', 'questions', 'family-friends'),
('A family member needs emotional support during a crisis. How do you show up for them?', 'situations', 'family-friends'),
('Would you rather have friends who are very similar to you or completely different?', 'dilemmas', 'family-friends'),
('How do you preserve family stories for future generations?', 'questions', 'family-friends'),
('Your friend group is divided over a misunderstanding. How do you help mend the rift?', 'situations', 'family-friends'),
('Is family more about who you''re born with or who you choose to surround yourself with?', 'dilemmas', 'family-friends'),
('What''s a family member''s quirk that you''ve come to love over time?', 'questions', 'family-friends'),
('You''re planning a surprise for a friend who''s been down lately. What do you do to lift their spirits?', 'situations', 'family-friends'),
('Would you sacrifice a personal goal to help a family member achieve theirs?', 'dilemmas', 'family-friends'),
('How do you help a friend see their own potential when they''re full of self-doubt?', 'questions', 'family-friends'),
('A family member shares a difficult truth about their past. How do you respond with empathy?', 'situations', 'family-friends'),
('Is it better to have frequent short visits with family or rare but longer ones?', 'dilemmas', 'family-friends'),
('What''s a time a friend''s kindness completely changed your day?', 'questions', 'family-friends'),
('You''re organizing a family trip, but preferences clash. How do you find a destination everyone loves?', 'situations', 'family-friends'),
('Would you rather confide in a family member or a trusted friend about a personal struggle?', 'dilemmas', 'family-friends'),
('How do you stay connected to family traditions while creating your own path?', 'questions', 'family-friends'),
('A friend is hesitant to join a group outing due to anxiety. How do you encourage them without pushing too hard?', 'situations', 'family-friends'),
('Is it more important for friends to share your interests or your values?', 'dilemmas', 'family-friends'),
('What''s a family bond that grew stronger after overcoming a hardship together?', 'questions', 'family-friends'),
('Your family is debating a sensitive topic at dinner. How do you steer the conversation to avoid conflict?', 'situations', 'family-friends'),
('Would you rather have a tight-knit family with few friends or a small family with many friends?', 'dilemmas', 'family-friends'),
('How do you make time for friends when family responsibilities pile up?', 'questions', 'family-friends'),
('A family member feels left out during gatherings. How do you ensure they feel included?', 'situations', 'family-friends'),
('Is it harder to maintain long-distance friendships or family relationships?', 'dilemmas', 'family-friends'),
('What''s a family value you didn''t appreciate until you were older?', 'questions', 'family-friends'),
('You learn a friend is facing a challenge they haven''t shared. How do you offer support without prying?', 'situations', 'family-friends'),
('Would you choose to spend your last day with family or your closest friends?', 'dilemmas', 'family-friends'),
('How do you teach younger family members about the importance of strong friendships?', 'questions', 'family-friends'),
('Your family inherits a property everyone wants for different reasons. How do you mediate the discussion?', 'situations', 'family-friends'),
('Is it more fulfilling to help a friend through a crisis or celebrate their success?', 'dilemmas', 'family-friends'),
('What''s a family ritual that always brings a sense of comfort or belonging?', 'questions', 'family-friends'),
('A friend achieves something you''ve been striving for. How do you handle mixed feelings of joy and envy?', 'situations', 'family-friends'),
('Would you rather have family traditions that never change or evolve with each generation?', 'dilemmas', 'family-friends'),
('How do you rebuild a strained relationship with a family member over time?', 'questions', 'family-friends'),
('You''re paired with a shy family member for a group activity. How do you help them feel at ease?', 'situations', 'family-friends'),
('Is it more important to have friends who inspire you or comfort you?', 'dilemmas', 'family-friends'),
('What''s a time a family member''s forgiveness taught you about grace?', 'questions', 'family-friends'),
('A friend is overworking themselves. How do you convince them to take a much-needed break?', 'situations', 'family-friends'),
('Would you prioritize a family emergency over a long-planned event with friends?', 'dilemmas', 'family-friends'),
('How do you create new family memories that future generations will cherish?', 'questions', 'family-friends'),
('Your family is hosting a cultural exchange with another family. How do you share your traditions?', 'situations', 'family-friends'),
('Is it better to have a few deep family connections or many casual ones?', 'dilemmas', 'family-friends'),
('What''s a friend''s story of resilience that motivates you to keep going?', 'questions', 'family-friends'),
('A family member is reluctant to try new technology to stay connected. How do you gently encourage them?', 'situations', 'family-friends'),
('Would you rather share all your life updates with family or keep some things private?', 'dilemmas', 'family-friends'),
('How do you ensure a friend knows they can always count on you, no matter the distance?', 'questions', 'family-friends');

-- Note: Due to token limitations, I'll stop here for the first category. The script would continue with 100 carefully crafted content items for each of the remaining categories (dating-relationship, fiction, only-wrong-answers, travel, money, 18+, randomized), ensuring a mix of types (questions, situations, dilemmas) and deep relevance to each category's theme. A separate script or follow-up can be generated for the remaining content.

-- Re-enable RLS (policy already exists)
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
