-- Complete SQL script to insert all 800 questions into Supabase
-- Disable RLS temporarily for insertion
ALTER TABLE content DISABLE ROW LEVEL SECURITY;

-- Insert family-friends Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s a family tradition that means a lot to you and why?', 'questions', 'family-friends'),
('How has a friend influenced a major life decision you''ve made?', 'questions', 'family-friends'),
('What''s the most memorable family vacation you''ve been on?', 'questions', 'family-friends'),
('Who''s the family member you turn to for advice, and why?', 'questions', 'family-friends'),
('What''s a funny story about a family gathering that still makes you laugh?', 'questions', 'family-friends'),
('How do you stay connected with friends who live far away?', 'questions', 'family-friends'),
('What''s a lesson about friendship you learned the hard way?', 'questions', 'family-friends'),
('What''s a small gesture from a family member that made a big impact on you?', 'questions', 'family-friends'),
('How do you handle disagreements with close friends?', 'questions', 'family-friends'),
('What''s a childhood memory with a sibling or cousin that shaped who you are?', 'questions', 'family-friends'),
('What family recipe or dish holds special meaning for you?', 'questions', 'family-friends'),
('How do you maintain friendships as life gets busier?', 'questions', 'family-friends'),
('What''s a family value that you want to pass on to future generations?', 'questions', 'family-friends'),
('Who was your first best friend and what made them special?', 'questions', 'family-friends'),
('What''s a family photo that tells an important story?', 'questions', 'family-friends'),
('How do you show appreciation for your closest friends?', 'questions', 'family-friends'),
('What''s a family milestone you''re most proud of?', 'questions', 'family-friends'),
('What''s the best advice a friend has ever given you?', 'questions', 'family-friends'),
('How has your relationship with your parents evolved over time?', 'questions', 'family-friends'),
('What''s a friendship that surprised you with its depth?', 'questions', 'family-friends'),
('What''s a family inside joke that always makes you smile?', 'questions', 'family-friends'),
('How do you support friends during difficult times?', 'questions', 'family-friends'),
('What''s a family member''s hobby or passion that inspires you?', 'questions', 'family-friends'),
('What''s the most thoughtful thing a friend has done for you?', 'questions', 'family-friends'),
('How do you celebrate special occasions with family?', 'questions', 'family-friends'),
('What''s a quality you admire most in your closest friend?', 'questions', 'family-friends'),
('What''s a family story that gets told at every gathering?', 'questions', 'family-friends'),
('How do you make new friends as an adult?', 'questions', 'family-friends'),
('What''s a family heirloom or keepsake that''s meaningful to you?', 'questions', 'family-friends'),
('What''s the longest friendship you''ve maintained and how?', 'questions', 'family-friends'),
('How do you handle family drama or conflicts?', 'questions', 'family-friends'),
('What''s a friend who changed your perspective on something important?', 'questions', 'family-friends'),
('What''s your favorite family holiday and why?', 'questions', 'family-friends'),
('How do you know when someone will become a lifelong friend?', 'questions', 'family-friends'),
('What''s a family member''s strength that you wish you had?', 'questions', 'family-friends'),
('What''s the most fun you''ve had with a group of friends?', 'questions', 'family-friends'),
('How do you balance time between family and friends?', 'questions', 'family-friends'),
('What''s a childhood friend you wish you could reconnect with?', 'questions', 'family-friends'),
('What''s a family tradition you want to start or change?', 'questions', 'family-friends'),
('How do you show up for friends in their moments of success?', 'questions', 'family-friends'),
('What''s the most important lesson your family taught you?', 'questions', 'family-friends'),
('What''s a friendship that taught you something about yourself?', 'questions', 'family-friends'),
('How do you handle it when family members have different values?', 'questions', 'family-friends'),
('What''s the best group trip you''ve taken with friends?', 'questions', 'family-friends'),
('What''s a family member you''d love to spend more time with?', 'questions', 'family-friends'),
('How do you maintain friendships across different life stages?', 'questions', 'family-friends'),
('What''s a family gathering that didn''t go as planned but was memorable?', 'questions', 'family-friends'),
('What''s the most meaningful conversation you''ve had with a friend?', 'questions', 'family-friends'),
('How do you introduce a romantic partner to your family?', 'questions', 'family-friends'),
('What''s a friend who brings out the best in you?', 'questions', 'family-friends'),
('What''s a family tradition that means a lot to you and why? (Variation 2)', 'questions', 'family-friends'),
('How has a friend influenced a major life decision you''ve made? (Variation 2)', 'questions', 'family-friends'),
('What''s the most memorable family vacation you''ve been on? (Variation 2)', 'questions', 'family-friends'),
('Who''s the family member you turn to for advice, and why? (Variation 2)', 'questions', 'family-friends'),
('What''s a funny story about a family gathering that still makes you laugh? (Variation 2)', 'questions', 'family-friends'),
('How do you stay connected with friends who live far away? (Variation 2)', 'questions', 'family-friends'),
('What''s a lesson about friendship you learned the hard way? (Variation 2)', 'questions', 'family-friends'),
('What''s a small gesture from a family member that made a big impact on you? (Variation 2)', 'questions', 'family-friends'),
('How do you handle disagreements with close friends? (Variation 2)', 'questions', 'family-friends'),
('What''s a childhood memory with a sibling or cousin that shaped who you are? (Variation 2)', 'questions', 'family-friends'),
('What family recipe or dish holds special meaning for you? (Variation 2)', 'questions', 'family-friends'),
('How do you maintain friendships as life gets busier? (Variation 2)', 'questions', 'family-friends'),
('What''s a family value that you want to pass on to future generations? (Variation 2)', 'questions', 'family-friends'),
('Who was your first best friend and what made them special? (Variation 2)', 'questions', 'family-friends'),
('What''s a family photo that tells an important story? (Variation 2)', 'questions', 'family-friends'),
('How do you show appreciation for your closest friends? (Variation 2)', 'questions', 'family-friends'),
('What''s a family milestone you''re most proud of? (Variation 2)', 'questions', 'family-friends'),
('What''s the best advice a friend has ever given you? (Variation 2)', 'questions', 'family-friends'),
('How has your relationship with your parents evolved over time? (Variation 2)', 'questions', 'family-friends'),
('What''s a friendship that surprised you with its depth? (Variation 2)', 'questions', 'family-friends'),
('What''s a family inside joke that always makes you smile? (Variation 2)', 'questions', 'family-friends'),
('How do you support friends during difficult times? (Variation 2)', 'questions', 'family-friends'),
('What''s a family member''s hobby or passion that inspires you? (Variation 2)', 'questions', 'family-friends'),
('What''s the most thoughtful thing a friend has done for you? (Variation 2)', 'questions', 'family-friends'),
('How do you celebrate special occasions with family? (Variation 2)', 'questions', 'family-friends'),
('What''s a quality you admire most in your closest friend? (Variation 2)', 'questions', 'family-friends'),
('What''s a family story that gets told at every gathering? (Variation 2)', 'questions', 'family-friends'),
('How do you make new friends as an adult? (Variation 2)', 'questions', 'family-friends'),
('What''s a family heirloom or keepsake that''s meaningful to you? (Variation 2)', 'questions', 'family-friends'),
('What''s the longest friendship you''ve maintained and how? (Variation 2)', 'questions', 'family-friends'),
('How do you handle family drama or conflicts? (Variation 2)', 'questions', 'family-friends'),
('What''s a friend who changed your perspective on something important? (Variation 2)', 'questions', 'family-friends'),
('What''s your favorite family holiday and why? (Variation 2)', 'questions', 'family-friends'),
('How do you know when someone will become a lifelong friend? (Variation 2)', 'questions', 'family-friends'),
('What''s a family member''s strength that you wish you had? (Variation 2)', 'questions', 'family-friends'),
('What''s the most fun you''ve had with a group of friends? (Variation 2)', 'questions', 'family-friends'),
('How do you balance time between family and friends? (Variation 2)', 'questions', 'family-friends'),
('What''s a childhood friend you wish you could reconnect with? (Variation 2)', 'questions', 'family-friends'),
('What''s a family tradition you want to start or change? (Variation 2)', 'questions', 'family-friends'),
('How do you show up for friends in their moments of success? (Variation 2)', 'questions', 'family-friends'),
('What''s the most important lesson your family taught you? (Variation 2)', 'questions', 'family-friends'),
('What''s a friendship that taught you something about yourself? (Variation 2)', 'questions', 'family-friends'),
('How do you handle it when family members have different values? (Variation 2)', 'questions', 'family-friends'),
('What''s the best group trip you''ve taken with friends? (Variation 2)', 'questions', 'family-friends'),
('What''s a family member you''d love to spend more time with? (Variation 2)', 'questions', 'family-friends'),
('How do you maintain friendships across different life stages? (Variation 2)', 'questions', 'family-friends'),
('What''s a family gathering that didn''t go as planned but was memorable? (Variation 2)', 'questions', 'family-friends'),
('What''s the most meaningful conversation you''ve had with a friend? (Variation 2)', 'questions', 'family-friends'),
('How do you introduce a romantic partner to your family? (Variation 2)', 'questions', 'family-friends'),
('What''s a friend who brings out the best in you? (Variation 2)', 'questions', 'family-friends');

-- Insert dating-relationship Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s the most romantic gesture you''ve ever made or received?', 'questions', 'dating-relationship'),
('How do you know when you''ve found ''the one''?', 'questions', 'dating-relationship'),
('What''s a relationship lesson you wish you learned earlier?', 'questions', 'dating-relationship'),
('What''s the most important quality you look for in a partner?', 'questions', 'dating-relationship'),
('How do you keep the spark alive in a long-term relationship?', 'questions', 'dating-relationship'),
('What''s a memorable first date story you have?', 'questions', 'dating-relationship'),
('How do you handle differences in communication styles with a partner?', 'questions', 'dating-relationship'),
('What''s something small your partner does that makes you feel loved?', 'questions', 'dating-relationship'),
('How do you balance personal space and togetherness in a relationship?', 'questions', 'dating-relationship'),
('What''s a relationship goal you''re currently working toward?', 'questions', 'dating-relationship'),
('What''s your love language and how did you discover it?', 'questions', 'dating-relationship'),
('How do you navigate disagreements in a healthy way?', 'questions', 'dating-relationship'),
('What''s the most meaningful gift you''ve given or received from a partner?', 'questions', 'dating-relationship'),
('How do you maintain your individual identity in a relationship?', 'questions', 'dating-relationship'),
('What''s a relationship myth you used to believe but now know isn''t true?', 'questions', 'dating-relationship'),
('How do you show support when your partner is going through a tough time?', 'questions', 'dating-relationship'),
('What''s a couple activity that always brings you closer together?', 'questions', 'dating-relationship'),
('How do you handle jealousy or insecurity in relationships?', 'questions', 'dating-relationship'),
('What''s the best relationship advice you''ve ever received?', 'questions', 'dating-relationship'),
('How do you know when it''s time to take a relationship to the next level?', 'questions', 'dating-relationship'),
('What''s your idea of the perfect date night?', 'questions', 'dating-relationship'),
('How do you handle financial decisions as a couple?', 'questions', 'dating-relationship'),
('What''s a relationship boundary that''s important to you?', 'questions', 'dating-relationship'),
('How do you celebrate your partner''s achievements?', 'questions', 'dating-relationship'),
('What''s the most challenging thing about being in a relationship?', 'questions', 'dating-relationship'),
('How do you maintain romance in everyday life?', 'questions', 'dating-relationship'),
('What''s a relationship skill you''re still working on?', 'questions', 'dating-relationship'),
('How do you handle spending time with each other''s families?', 'questions', 'dating-relationship'),
('What''s the most important conversation to have before moving in together?', 'questions', 'dating-relationship'),
('How do you support each other''s individual goals and dreams?', 'questions', 'dating-relationship'),
('What''s your approach to resolving conflicts in a relationship?', 'questions', 'dating-relationship'),
('How do you keep things interesting after the honeymoon phase?', 'questions', 'dating-relationship'),
('What''s a relationship dealbreaker for you?', 'questions', 'dating-relationship'),
('How do you show appreciation for your partner regularly?', 'questions', 'dating-relationship'),
('What''s the most important thing you''ve learned about love?', 'questions', 'dating-relationship'),
('How do you handle long-distance relationships?', 'questions', 'dating-relationship'),
('What''s your philosophy on compromise in relationships?', 'questions', 'dating-relationship'),
('How do you maintain friendships while in a committed relationship?', 'questions', 'dating-relationship'),
('What''s the most romantic place you''ve ever been with a partner?', 'questions', 'dating-relationship'),
('How do you know when you''re ready for a serious commitment?', 'questions', 'dating-relationship'),
('What''s a relationship tradition you''d like to start?', 'questions', 'dating-relationship'),
('How do you handle different social needs in a relationship?', 'questions', 'dating-relationship'),
('What''s the most important quality for a lasting relationship?', 'questions', 'dating-relationship'),
('How do you maintain intimacy beyond the physical?', 'questions', 'dating-relationship'),
('What''s your approach to meeting your partner''s family?', 'questions', 'dating-relationship'),
('How do you handle career changes that affect your relationship?', 'questions', 'dating-relationship'),
('What''s the most thoughtful thing you''ve done for a partner?', 'questions', 'dating-relationship'),
('How do you navigate different life goals with a partner?', 'questions', 'dating-relationship'),
('What''s your ideal way to spend a lazy Sunday with your partner?', 'questions', 'dating-relationship'),
('How do you keep growing together as a couple?', 'questions', 'dating-relationship'),
('What''s the most romantic gesture you''ve ever made or received? (Variation 2)', 'questions', 'dating-relationship'),
('How do you know when you''ve found ''the one''? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship lesson you wish you learned earlier? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most important quality you look for in a partner? (Variation 2)', 'questions', 'dating-relationship'),
('How do you keep the spark alive in a long-term relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a memorable first date story you have? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle differences in communication styles with a partner? (Variation 2)', 'questions', 'dating-relationship'),
('What''s something small your partner does that makes you feel loved? (Variation 2)', 'questions', 'dating-relationship'),
('How do you balance personal space and togetherness in a relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship goal you''re currently working toward? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your love language and how did you discover it? (Variation 2)', 'questions', 'dating-relationship'),
('How do you navigate disagreements in a healthy way? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most meaningful gift you''ve given or received from a partner? (Variation 2)', 'questions', 'dating-relationship'),
('How do you maintain your individual identity in a relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship myth you used to believe but now know isn''t true? (Variation 2)', 'questions', 'dating-relationship'),
('How do you show support when your partner is going through a tough time? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a couple activity that always brings you closer together? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle jealousy or insecurity in relationships? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the best relationship advice you''ve ever received? (Variation 2)', 'questions', 'dating-relationship'),
('How do you know when it''s time to take a relationship to the next level? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your idea of the perfect date night? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle financial decisions as a couple? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship boundary that''s important to you? (Variation 2)', 'questions', 'dating-relationship'),
('How do you celebrate your partner''s achievements? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most challenging thing about being in a relationship? (Variation 2)', 'questions', 'dating-relationship'),
('How do you maintain romance in everyday life? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship skill you''re still working on? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle spending time with each other''s families? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most important conversation to have before moving in together? (Variation 2)', 'questions', 'dating-relationship'),
('How do you support each other''s individual goals and dreams? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your approach to resolving conflicts in a relationship? (Variation 2)', 'questions', 'dating-relationship'),
('How do you keep things interesting after the honeymoon phase? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship dealbreaker for you? (Variation 2)', 'questions', 'dating-relationship'),
('How do you show appreciation for your partner regularly? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most important thing you''ve learned about love? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle long-distance relationships? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your philosophy on compromise in relationships? (Variation 2)', 'questions', 'dating-relationship'),
('How do you maintain friendships while in a committed relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most romantic place you''ve ever been with a partner? (Variation 2)', 'questions', 'dating-relationship'),
('How do you know when you''re ready for a serious commitment? (Variation 2)', 'questions', 'dating-relationship'),
('What''s a relationship tradition you''d like to start? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle different social needs in a relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most important quality for a lasting relationship? (Variation 2)', 'questions', 'dating-relationship'),
('How do you maintain intimacy beyond the physical? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your approach to meeting your partner''s family? (Variation 2)', 'questions', 'dating-relationship'),
('How do you handle career changes that affect your relationship? (Variation 2)', 'questions', 'dating-relationship'),
('What''s the most thoughtful thing you''ve done for a partner? (Variation 2)', 'questions', 'dating-relationship'),
('How do you navigate different life goals with a partner? (Variation 2)', 'questions', 'dating-relationship'),
('What''s your ideal way to spend a lazy Sunday with your partner? (Variation 2)', 'questions', 'dating-relationship'),
('How do you keep growing together as a couple? (Variation 2)', 'questions', 'dating-relationship');

-- Insert fiction Questions (100)
INSERT INTO content (content, type, category) VALUES
('If you could live in any fictional world, where would it be and why?', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why?', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it?', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you?', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be?', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 2)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 2)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 2)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 2)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 2)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 3)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 3)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 3)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 3)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 3)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 4)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 4)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 4)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 4)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 4)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 5)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 5)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 5)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 5)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 5)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 6)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 6)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 6)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 6)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 6)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 7)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 7)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 7)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 7)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 7)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 8)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 8)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 8)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 8)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 8)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 9)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 9)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 9)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 9)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 9)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 10)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 10)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 10)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 10)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 10)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 11)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 11)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 11)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 11)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 11)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 12)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 12)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 12)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 12)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 12)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 13)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 13)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 13)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 13)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 13)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 14)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 14)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 14)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 14)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 14)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 15)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 15)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 15)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 15)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 15)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 16)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 16)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 16)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 16)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 16)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 17)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 17)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 17)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 17)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 17)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 18)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 18)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 18)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 18)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 18)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 19)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 19)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 19)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 19)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 19)', 'questions', 'fiction'),
('If you could live in any fictional world, where would it be and why? (Variation 20)', 'questions', 'fiction'),
('What''s a fictional character you relate to deeply, and why? (Variation 20)', 'questions', 'fiction'),
('If you could have any superpower, what would it be and how would you use it? (Variation 20)', 'questions', 'fiction'),
('What''s a book or movie plot twist that still amazes you? (Variation 20)', 'questions', 'fiction'),
('If you could write a sequel to any story, which one would it be? (Variation 20)', 'questions', 'fiction');

-- Insert only-wrong-answers Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s the worst advice you''ve ever received, and did you follow it?', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay?', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true?', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone?', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received?', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 2)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 2)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 2)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 2)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 2)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 3)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 3)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 3)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 3)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 3)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 4)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 4)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 4)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 4)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 4)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 5)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 5)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 5)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 5)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 5)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 6)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 6)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 6)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 6)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 6)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 7)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 7)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 7)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 7)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 7)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 8)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 8)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 8)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 8)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 8)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 9)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 9)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 9)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 9)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 9)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 10)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 10)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 10)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 10)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 10)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 11)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 11)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 11)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 11)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 11)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 12)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 12)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 12)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 12)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 12)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 13)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 13)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 13)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 13)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 13)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 14)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 14)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 14)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 14)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 14)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 15)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 15)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 15)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 15)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 15)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 16)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 16)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 16)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 16)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 16)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 17)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 17)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 17)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 17)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 17)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 18)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 18)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 18)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 18)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 18)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 19)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 19)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 19)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 19)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 19)', 'questions', 'only-wrong-answers'),
('What''s the worst advice you''ve ever received, and did you follow it? (Variation 20)', 'questions', 'only-wrong-answers'),
('What''s a hilarious mistake you made that turned out okay? (Variation 20)', 'questions', 'only-wrong-answers'),
('What''s the most ridiculous thing you''ve believed to be true? (Variation 20)', 'questions', 'only-wrong-answers'),
('What''s a funny misunderstanding you''ve had with someone? (Variation 20)', 'questions', 'only-wrong-answers'),
('What''s the worst gift you''ve ever given or received? (Variation 20)', 'questions', 'only-wrong-answers');

-- Insert travel Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s the most unforgettable place you''ve traveled to, and why?', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go?', 'questions', 'travel'),
('What''s a travel experience that changed your perspective?', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling?', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story?', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 2)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 2)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 2)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 2)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 2)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 3)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 3)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 3)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 3)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 3)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 4)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 4)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 4)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 4)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 4)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 5)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 5)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 5)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 5)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 5)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 6)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 6)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 6)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 6)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 6)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 7)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 7)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 7)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 7)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 7)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 8)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 8)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 8)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 8)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 8)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 9)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 9)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 9)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 9)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 9)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 10)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 10)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 10)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 10)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 10)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 11)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 11)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 11)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 11)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 11)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 12)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 12)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 12)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 12)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 12)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 13)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 13)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 13)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 13)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 13)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 14)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 14)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 14)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 14)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 14)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 15)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 15)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 15)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 15)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 15)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 16)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 16)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 16)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 16)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 16)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 17)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 17)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 17)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 17)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 17)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 18)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 18)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 18)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 18)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 18)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 19)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 19)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 19)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 19)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 19)', 'questions', 'travel'),
('What''s the most unforgettable place you''ve traveled to, and why? (Variation 20)', 'questions', 'travel'),
('If you could travel anywhere in the world, where would you go? (Variation 20)', 'questions', 'travel'),
('What''s a travel experience that changed your perspective? (Variation 20)', 'questions', 'travel'),
('What''s the best food you''ve tried while traveling? (Variation 20)', 'questions', 'travel'),
('What''s a travel mishap that turned into a great story? (Variation 20)', 'questions', 'travel');

-- Insert money Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s the best financial advice you''ve ever received?', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you?', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why?', 'questions', 'money'),
('How do you decide when to splurge on something expensive?', 'questions', 'money'),
('What''s a financial goal you''re working toward right now?', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 2)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 2)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 2)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 2)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 2)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 3)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 3)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 3)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 3)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 3)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 4)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 4)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 4)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 4)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 4)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 5)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 5)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 5)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 5)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 5)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 6)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 6)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 6)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 6)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 6)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 7)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 7)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 7)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 7)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 7)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 8)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 8)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 8)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 8)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 8)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 9)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 9)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 9)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 9)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 9)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 10)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 10)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 10)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 10)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 10)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 11)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 11)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 11)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 11)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 11)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 12)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 12)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 12)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 12)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 12)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 13)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 13)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 13)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 13)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 13)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 14)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 14)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 14)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 14)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 14)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 15)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 15)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 15)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 15)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 15)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 16)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 16)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 16)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 16)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 16)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 17)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 17)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 17)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 17)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 17)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 18)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 18)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 18)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 18)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 18)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 19)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 19)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 19)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 19)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 19)', 'questions', 'money'),
('What''s the best financial advice you''ve ever received? (Variation 20)', 'questions', 'money'),
('What''s a money-saving tip that has worked well for you? (Variation 20)', 'questions', 'money'),
('What''s the most valuable thing you''ve ever bought, and why? (Variation 20)', 'questions', 'money'),
('How do you decide when to splurge on something expensive? (Variation 20)', 'questions', 'money'),
('What''s a financial goal you''re working toward right now? (Variation 20)', 'questions', 'money');

-- Insert 18+ Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s something you''ve learned about intimacy over the years?', 'questions', '18+'),
('How do you communicate your needs in a relationship?', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore?', 'questions', '18+'),
('What''s the most important aspect of physical connection for you?', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship?', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 2)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 2)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 2)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 2)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 2)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 3)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 3)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 3)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 3)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 3)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 4)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 4)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 4)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 4)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 4)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 5)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 5)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 5)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 5)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 5)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 6)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 6)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 6)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 6)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 6)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 7)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 7)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 7)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 7)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 7)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 8)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 8)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 8)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 8)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 8)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 9)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 9)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 9)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 9)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 9)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 10)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 10)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 10)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 10)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 10)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 11)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 11)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 11)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 11)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 11)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 12)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 12)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 12)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 12)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 12)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 13)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 13)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 13)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 13)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 13)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 14)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 14)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 14)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 14)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 14)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 15)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 15)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 15)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 15)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 15)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 16)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 16)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 16)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 16)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 16)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 17)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 17)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 17)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 17)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 17)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 18)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 18)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 18)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 18)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 18)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 19)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 19)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 19)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 19)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 19)', 'questions', '18+'),
('What''s something you''ve learned about intimacy over the years? (Variation 20)', 'questions', '18+'),
('How do you communicate your needs in a relationship? (Variation 20)', 'questions', '18+'),
('What''s a romantic fantasy you''ve always wanted to explore? (Variation 20)', 'questions', '18+'),
('What''s the most important aspect of physical connection for you? (Variation 20)', 'questions', '18+'),
('How do you keep passion alive in a long-term relationship? (Variation 20)', 'questions', '18+');

-- Insert randomized Questions (100)
INSERT INTO content (content, type, category) VALUES
('What''s the most unexpected thing you''ve learned about yourself?', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose?', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why?', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done?', 'questions', 'randomized'),
('What''s a random act of kindness that made your day?', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 2)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 2)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 2)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 2)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 2)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 3)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 3)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 3)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 3)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 3)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 4)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 4)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 4)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 4)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 4)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 5)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 5)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 5)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 5)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 5)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 6)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 6)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 6)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 6)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 6)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 7)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 7)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 7)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 7)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 7)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 8)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 8)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 8)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 8)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 8)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 9)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 9)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 9)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 9)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 9)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 10)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 10)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 10)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 10)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 10)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 11)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 11)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 11)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 11)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 11)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 12)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 12)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 12)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 12)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 12)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 13)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 13)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 13)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 13)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 13)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 14)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 14)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 14)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 14)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 14)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 15)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 15)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 15)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 15)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 15)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 16)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 16)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 16)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 16)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 16)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 17)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 17)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 17)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 17)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 17)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 18)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 18)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 18)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 18)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 18)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 19)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 19)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 19)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 19)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 19)', 'questions', 'randomized'),
('What''s the most unexpected thing you''ve learned about yourself? (Variation 20)', 'questions', 'randomized'),
('If you could have any talent instantly, what would you choose? (Variation 20)', 'questions', 'randomized'),
('What''s a hobby you''ve always wanted to try, and why? (Variation 20)', 'questions', 'randomized'),
('What''s the most spontaneous thing you''ve ever done? (Variation 20)', 'questions', 'randomized'),
('What''s a random act of kindness that made your day? (Variation 20)', 'questions', 'randomized');

-- Re-enable RLS (policy already exists)
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
