-- Family & Friends - 100 Questions
-- Insert statements for Supabase content table

INSERT INTO content (content, type, category) VALUES
('What''s the most valuable lesson your parents taught you?', 'questions', 'family-friends'),
('If you could have dinner with any family member who has passed away, who would it be?', 'questions', 'family-friends'),
('What''s your favorite childhood memory with your siblings?', 'questions', 'family-friends'),
('Which friend has had the biggest impact on your life?', 'questions', 'family-friends'),
('What''s the best advice a friend has ever given you?', 'questions', 'family-friends'),
('If you could relive one day with your family, which would it be?', 'questions', 'family-friends'),
('What''s something you wish you could tell your younger self about friendship?', 'questions', 'family-friends'),
('Which family tradition means the most to you?', 'questions', 'family-friends'),
('What''s the funniest thing that happened at a family gathering?', 'questions', 'family-friends'),
('If you could give your best friend a superpower, what would it be?', 'questions', 'family-friends'),
('What''s the most embarrassing thing your family knows about you?', 'questions', 'family-friends'),
('Which friend do you trust with your deepest secrets?', 'questions', 'family-friends'),
('What''s your favorite way to spend time with your family?', 'questions', 'family-friends'),
('If you could change one thing about your childhood, what would it be?', 'questions', 'family-friends'),
('What''s the most thoughtful gift you''ve ever received from a friend?', 'questions', 'family-friends'),
('Which family member are you most similar to?', 'questions', 'family-friends'),
('What''s the longest friendship you''ve maintained?', 'questions', 'family-friends'),
('If your family had a motto, what would it be?', 'questions', 'family-friends'),
('What''s something you''ve learned from watching your parents'' relationship?', 'questions', 'family-friends'),
('Which friend would you want by your side in a crisis?', 'questions', 'family-friends'),
('What''s your favorite family recipe or dish?', 'questions', 'family-friends'),
('If you could introduce your childhood self to your current friends, what would happen?', 'questions', 'family-friends'),
('What''s the most important quality you look for in a friend?', 'questions', 'family-friends'),
('Which family member gives the best hugs?', 'questions', 'family-friends'),
('What''s something you''ve never told your best friend?', 'questions', 'family-friends'),
('If you could have grown up in a different family, would you?', 'questions', 'family-friends'),
('What''s the most fun you''ve ever had with friends?', 'questions', 'family-friends'),
('Which family member would you choose to be stranded on an island with?', 'questions', 'family-friends'),
('What''s the biggest sacrifice a friend has made for you?', 'questions', 'family-friends'),
('If you could ask your grandparents one question, what would it be?', 'questions', 'family-friends'),
('What''s your favorite inside joke with friends?', 'questions', 'family-friends'),
('Which family member has the best sense of humor?', 'questions', 'family-friends'),
('What''s something you wish your friends knew about you?', 'questions', 'family-friends'),
('If you could plan the perfect family vacation, where would you go?', 'questions', 'family-friends'),
('What''s the most adventurous thing you''ve done with friends?', 'questions', 'family-friends'),
('Which family member would you want to switch lives with for a day?', 'questions', 'family-friends'),
('What''s the best compliment you''ve ever received from a friend?', 'questions', 'family-friends'),
('If you could give your family one piece of advice, what would it be?', 'questions', 'family-friends'),
('What''s your favorite memory from a sleepover or hangout?', 'questions', 'family-friends'),
('Which family member are you most proud of?', 'questions', 'family-friends'),
('What''s something you''ve learned from losing a friendship?', 'questions', 'family-friends'),
('If you could create a new family tradition, what would it be?', 'questions', 'family-friends'),
('What''s the most spontaneous thing you''ve done with friends?', 'questions', 'family-friends'),
('Which family member would make the best superhero?', 'questions', 'family-friends'),
('What''s your favorite way to celebrate with friends?', 'questions', 'family-friends'),
('If you could have any family member''s talent, whose would you choose?', 'questions', 'family-friends'),
('What''s the most meaningful conversation you''ve had with a friend?', 'questions', 'family-friends'),
('Which family gathering was the most memorable?', 'questions', 'family-friends'),
('What''s something you wish you could do more often with friends?', 'questions', 'family-friends'),
('If your family were a TV show, what genre would it be?', 'questions', 'family-friends'),
('What''s the best group trip you''ve taken with friends?', 'questions', 'family-friends'),
('Which family member gives the best advice?', 'questions', 'family-friends'),
('What''s your favorite thing about your friend group?', 'questions', 'family-friends'),
('If you could have dinner with your family from 10 years ago, what would you talk about?', 'questions', 'family-friends'),
('What''s the most creative gift you''ve given a friend?', 'questions', 'family-friends'),
('Which family member would you want as your teammate in a game show?', 'questions', 'family-friends'),
('What''s something you''ve always wanted to ask your parents?', 'questions', 'family-friends'),
('If you could give your friend group a name, what would it be?', 'questions', 'family-friends'),
('What''s your favorite family photo?', 'questions', 'family-friends'),
('Which friend has the most interesting family?', 'questions', 'family-friends'),
('If you could change one family rule from your childhood, what would it be?', 'questions', 'family-friends'),
('What''s the most ridiculous argument you''ve had with a friend?', 'questions', 'family-friends'),
('Which family member would survive longest in a zombie apocalypse?', 'questions', 'family-friends'),
('What''s your favorite tradition you''ve started with friends?', 'questions', 'family-friends'),
('If you could bring one family member to meet your friends, who would it be?', 'questions', 'family-friends'),
('What''s the most embarrassing thing you''ve done in front of friends?', 'questions', 'family-friends'),
('Which family member would you want to write your biography?', 'questions', 'family-friends'),
('What''s your favorite memory from a birthday celebration with friends?', 'questions', 'family-friends'),
('If your family had a theme song, what would it be?', 'questions', 'family-friends'),
('What''s the most supportive thing a friend has done for you?', 'questions', 'family-friends'),
('Which family member would make the best roommate?', 'questions', 'family-friends'),
('What''s your favorite way to make new friends?', 'questions', 'family-friends'),
('If you could have a family reunion anywhere, where would it be?', 'questions', 'family-friends'),
('What''s the most unusual friendship you''ve ever had?', 'questions', 'family-friends'),
('Which family member has changed the most over the years?', 'questions', 'family-friends'),
('What''s your favorite memory of helping a friend?', 'questions', 'family-friends'),
('If you could give your younger sibling advice, what would it be?', 'questions', 'family-friends'),
('What''s the most fun family game night you''ve ever had?', 'questions', 'family-friends'),
('Which friend would you want to be neighbors with?', 'questions', 'family-friends'),
('What''s your favorite family inside joke?', 'questions', 'family-friends'),
('If you could plan the perfect friend''s birthday party, what would you do?', 'questions', 'family-friends'),
('Which family member would you want to go on a road trip with?', 'questions', 'family-friends'),
('What''s the most meaningful gift you''ve given a friend?', 'questions', 'family-friends'),
('If your family were a band, what would your roles be?', 'questions', 'family-friends'),
('What''s your favorite memory of laughing with friends?', 'questions', 'family-friends'),
('Which family member would you want to learn a skill from?', 'questions', 'family-friends'),
('What''s the best surprise you''ve ever planned for a friend?', 'questions', 'family-friends'),
('If you could have any family member''s job for a day, whose would you choose?', 'questions', 'family-friends'),
('What''s your favorite way to stay in touch with distant friends?', 'questions', 'family-friends'),
('Which family member would you want to take a cooking class with?', 'questions', 'family-friends'),
('What''s the most important thing friendship has taught you?', 'questions', 'family-friends'),
('If you could have a family talent show, what would your act be?', 'questions', 'family-friends'),
('What''s your favorite memory of a friend visiting your family?', 'questions', 'family-friends'),
('Which family member would make the best teacher?', 'questions', 'family-friends'),
('What''s the most challenging thing about maintaining friendships?', 'questions', 'family-friends'),
('If you could create a family time capsule, what would you put in it?', 'questions', 'family-friends'),
('What''s your favorite quality that you''ve inherited from your family?', 'questions', 'family-friends'),
('Which friend has taught you the most about yourself?', 'questions', 'family-friends'),
('What''s your favorite family holiday tradition?', 'questions', 'family-friends'),
('If you could give all your friends one superpower, what would it be?', 'questions', 'family-friends'),
('Which family member would you want to start a business with?', 'questions', 'family-friends'),
('What''s the most beautiful thing about your closest friendship?', 'questions', 'family-friends'),
('If your family had a reality show, what would it be called?', 'questions', 'family-friends'),
('What''s your favorite memory of growing up with your family?', 'questions', 'family-friends');
