-- Family & Friends - 100 Situations
-- Insert statements for Supabase content table

INSERT INTO content (type, category, text, created_at) VALUES
('SITUATION', 'Family & Friends', 'Your best friend shows up at your door at 2 AM crying. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You walk in on your sibling going through your personal belongings. How do you handle it?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend asks to borrow $500 but you know they have a gambling problem. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your family is having a heated argument at dinner and everyone looks to you to take sides. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your friend has been lying about their job for months. How do you address it?', NOW()),
('SITUATION', 'Family & Friends', 'Your parent calls you crying about their marriage problems. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is planning a trip but deliberately didn''t invite one person. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your sibling is being bullied at school but they made you promise not to tell anyone. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend starts dating your ex without telling you first. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member asks you to lie to their spouse about their whereabouts. What do you say?', NOW()),
('SITUATION', 'Family & Friends', 'You witness your friend shoplifting while you''re together. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to drop out of college but hasn''t told your parents who are paying for it. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is driving under the influence and insists on giving you a ride home. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is having an affair. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend asks you to be their alibi for something you know is wrong. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your parent asks you to choose between them and your other parent in their divorce. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend has been spreading rumors about you. How do you address it?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is stealing money from your parents'' wallet. What''s your next move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to copy your homework for an important assignment. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You accidentally broke something valuable at a friend''s house and they haven''t noticed yet. How do you handle it?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is struggling with addiction but refuses to get help. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to cheat on their partner and wants your advice. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'You walk into a room and your family members stop talking, clearly having discussed you. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend borrowed your car and returned it damaged without mentioning it. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is being pressured into something dangerous by their friends. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is lying about their qualifications on job applications. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your family is planning a surprise party for someone who hates surprises. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend asks you to hide them from their ex who is looking for them. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your sibling is being cyberbullied but they don''t want your help. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to set you up with someone you''re not interested in and won''t take no for an answer. How do you handle it?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member asks you to keep a secret that could hurt someone else. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to quit their job without notice during a busy period. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to tell your parents about your secret relationship. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is excluding someone because of their political views. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is gambling away their savings. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to use your employee discount to buy expensive items for themselves. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your parent shows clear favoritism toward your sibling. How do you address it?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend has been reading your private messages. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is planning to elope without telling your family. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is being catfished online but won''t listen to your warnings. What''s your next move?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is spreading false information about another family member. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to copy your creative work and present it as their own. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'You witness your sibling being discriminated against but they ask you not to get involved. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to break up with their partner via text message. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family is planning to uninvite someone from a family event due to personal conflict. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to vandalize property as revenge. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to move back home as an adult, which would strain your parents financially. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend asks you to lie to their boss about why they missed work. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is in an abusive relationship but they won''t leave. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to borrow your expensive camera but you don''t trust them with it. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is hiding a serious medical condition from your parents. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to take credit for a group project they barely contributed to. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member wants to cut contact with another family member and wants your support. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is considering having a child to save their failing relationship. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'You walk in on your sibling going through your parents'' private documents. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is planning a prank that could seriously hurt someone. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is planning to make a major financial decision without consulting their spouse. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is lying about their age to date someone much older. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to tell your parents about your mental health struggles without your permission. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to ghost someone they''ve been dating for months. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is stealing from their workplace. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to reconcile with someone who hurt them badly in the past. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is planning to reveal a family secret at a public event. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to cheat on an important exam. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member asks you to spy on your sibling''s activities. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is considering taking a job that requires them to move away from their sick parent. What''s your advice?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your sibling is being pressured into illegal activities by their friends. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to use your identity for something questionable. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is planning to disinherit another family member and wants your opinion. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to take revenge on someone who wronged them. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to tell your parents about your friend''s illegal activities. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is planning to boycott a business owned by someone you know personally. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is planning to surprise someone with a visit that would be unwelcome. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to adopt a pet they clearly can''t properly care for. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is planning to tell your parents about your past mistakes to deflect from their own. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is considering dropping out of a commitment that would disappoint many people. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member wants to sell a family heirloom without consulting other family members. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to make a public statement about a controversial topic that could affect their career. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your sibling is planning to move far away without telling your parents. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to break up with their partner right before a major event in their partner''s life. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is planning to cut financial support to another struggling family member. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is considering plastic surgery for all the wrong reasons. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to borrow a significant amount of money but has a history of not paying back loans. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is planning to do something that could get you all in serious trouble. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is planning to make a public accusation without solid proof. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to reconnect with a toxic family member who hurt them in the past. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is planning to tell your parents about your secret hobby they disapprove of. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is considering taking a job that would require them to compromise their values. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member wants to exclude you from a family event because of a past disagreement. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to end their relationship in a way that would publicly humiliate their partner. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your sibling is hiding their sexual orientation from your family. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to tell their ex''s new partner about their ex''s flaws. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is planning to make a decision that goes against their spouse''s wishes. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to lie about their qualifications to get into a program. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to tell your parents about your financial struggles without your permission. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend group is planning to confront someone who hurt one of you, but it could escalate badly. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member wants to cut contact with you because of your life choices. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is considering taking a stand on an issue that could cost them their job. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling is planning to surprise your parents with news you know will upset them. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is considering ending a long-term friendship over a minor disagreement. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member wants to reveal a secret about another family member at a gathering. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is planning to make a major life change without consulting anyone who cares about them. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your sibling is planning to elope with someone your family has never met. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend wants to quit therapy against professional advice. What''s your response?', NOW()),
('SITUATION', 'Family & Friends', 'Your family member is planning to make a public statement that could affect the whole family. What do you do?', NOW()),
('SITUATION', 'Family & Friends', 'You find out your friend is planning to drop out of school against their parents'' wishes. How do you handle this?', NOW()),
('SITUATION', 'Family & Friends', 'Your sibling wants to cover for you while you sneak out, but it could get them in trouble. What''s your move?', NOW()),
('SITUATION', 'Family & Friends', 'Your friend is being racist in front of you and expects you to agree. How do you respond?', NOW()),
('SITUATION', 'Family & Friends', 'You discover your family member is planning to uninvite someone from a wedding due to personal drama. What do you do?', NOW());
