-- Family & Friends - 100 Dilemmas
-- Insert statements for Supabase content table

INSERT INTO content (type, category, text, created_at) VALUES
('DILEMMA', 'Family & Friends', 'Your best friend asks you to lie to their partner about where they were last night. Do you lie or tell the truth?', NOW()),
('DILEMMA', 'Family & Friends', 'You discover your sibling is stealing money from your parents. Do you confront them or tell your parents?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is dating someone you know is cheating on them. Do you tell them or stay out of it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family disapproves of your best friend. Do you defend your friend or keep the peace?', NOW()),
('DILEMMA', 'Family & Friends', 'You find out your friend has been talking behind your back. Do you confront them or end the friendship?', NOW()),
('DILEMMA', 'Family & Friends', 'Your parent asks you to choose between them and your other parent in their divorce. What do you do?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend borrowed money and won''t pay it back. Do you demand it or let it go?', NOW()),
('DILEMMA', 'Family & Friends', 'You witness your cousin shoplifting. Do you stop them or pretend you didn''t see?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to copy your homework. Do you let them or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is struggling with addiction but refuses help. Do you intervene or respect their choice?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to quit their job without notice. Do you support them or advise against it?', NOW()),
('DILEMMA', 'Family & Friends', 'You accidentally broke something valuable at a friend''s house. Do you confess or hope they don''t notice?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to borrow your car but you know they''re a reckless driver. Do you lend it or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is spreading rumors about another friend. Do you defend the absent friend or stay neutral?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family wants you to attend a gathering but your friend needs support during a crisis. Who do you choose?', NOW()),
('DILEMMA', 'Family & Friends', 'You discover your friend is lying about their qualifications on job applications. Do you report it or ignore it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your parent asks you to spy on your sibling''s activities. Do you agree or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to set you up with someone you''re not interested in. Do you go along or decline?', NOW()),
('DILEMMA', 'Family & Friends', 'You find out your family member is having an affair. Do you tell their spouse or keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend asks you to be their alibi for something illegal. Do you help or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is being bullied but asks you not to get involved. Do you respect their wishes or intervene?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to drop out of school against their parents'' wishes. Do you support them or discourage them?', NOW()),
('DILEMMA', 'Family & Friends', 'You witness your friend being racist. Do you call them out or avoid confrontation?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member asks you to lie about their whereabouts to their spouse. Do you lie or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is dating your ex and didn''t tell you. Do you confront them or end the friendship?', NOW()),
('DILEMMA', 'Family & Friends', 'Your parent favors your sibling over you. Do you address it or accept it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to use your employee discount for expensive items. Do you allow it or say no?', NOW()),
('DILEMMA', 'Family & Friends', 'You discover your family member is stealing from their workplace. Do you report it or talk to them first?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to cheat on an important exam. Do you try to stop them or mind your own business?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling asks you to cover for them while they sneak out. Do you help or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is excluding someone you like. Do you include them or go along with the group?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is in an abusive relationship but won''t leave. Do you intervene or respect their autonomy?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to borrow your expensive item but you don''t trust them with it. Do you lend it or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'You find out your sibling is pregnant and hiding it from your parents. Do you keep their secret or encourage them to tell?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is driving under the influence and wants to give you a ride. Do you get in or find another way?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member asks you to choose between two family events on the same day. Which do you choose?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is being catfished online but won''t listen to your warnings. Do you prove it or let them learn?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to elope without telling your parents. Do you support them or try to stop them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend asks you to lie to their boss about why they missed work. Do you lie or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'You discover your family member is gambling away their savings. Do you intervene or let them handle it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to copy your creative work and present it as their own. Do you allow it or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your parent asks you to choose between them and your grandparent in a family dispute. What do you do?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to vandalize property. Do you try to stop them or distance yourself?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to tell your parents about your secret relationship. Do you tell them first or ask them to keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning something that makes you uncomfortable. Do you participate or opt out?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is spreading false information about another family member. Do you correct them or stay out of it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to use your identity for something questionable. Do you help or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'You find out your sibling is being cyberbullied but they don''t want help. Do you intervene or respect their wishes?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to break up with their partner via text. Do you advise against it or support their choice?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member asks you to keep a secret that could hurt someone else. Do you keep it or reveal it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to quit therapy against professional advice. Do you support them or encourage them to continue?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to move far away without telling your parents. Do you encourage honesty or keep their secret?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering plastic surgery for the wrong reasons. Do you support them or try to dissuade them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to cut contact with another family member and wants your support. Do you take sides or stay neutral?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to confront someone who hurt them in a potentially dangerous way. Do you support them or try to stop them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to drop out of college but hasn''t told your parents who are paying for it. Do you encourage honesty or keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group wants to exclude someone because of their political views. Do you go along or defend them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to make a major financial decision without consulting their spouse. Do you advise them to discuss it or stay out of it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to reconcile with someone who hurt them badly. Do you support them or advise against it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is hiding a serious medical condition from your parents. Do you respect their privacy or encourage disclosure?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to take credit for a group project they barely contributed to. Do you call them out or let it slide?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to uninvite someone from a family event due to personal conflict. Do you support them or advocate for inclusion?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering having a child to save their relationship. Do you support them or express concerns?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to tell your parents about your mental health struggles without your permission. Do you tell them first or ask them to keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning to prank someone in a way that could be harmful. Do you participate or try to stop them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to surprise someone with a visit that you know would be unwelcome. Do you warn the person or let it happen?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to lie about their age to get into a relationship with someone much older. Do you support them or try to stop them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to reveal a family secret at a public event. Do you try to stop them or let them proceed?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering taking a job that would require them to move away from their sick parent. Do you advise them to take it or stay?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to cut financial support to another family member who is struggling. Do you support them or advocate for continued help?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to ghost someone they''ve been dating for months. Do you advise against it or support their choice?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to tell your parents about your friend''s illegal activities. Do you ask them to keep quiet or let them tell?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning to boycott a business owned by someone you know personally. Do you participate or abstain?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to disinherit another family member and wants your opinion. Do you give it or stay neutral?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to adopt a pet they can''t properly care for. Do you support them or try to dissuade them?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to elope with someone your family has never met. Do you support them or try to delay it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering dropping out of a commitment that would disappoint many people. Do you support them or encourage them to follow through?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to sell a family heirloom without consulting other family members. Do you support them or encourage discussion?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to take revenge on someone who wronged them. Do you support them or try to talk them out of it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to move back home as an adult, which would strain your parents'' finances. Do you support them or advise against it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning to exclude you from an event because of something you said. Do you apologize or defend yourself?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to make a public statement about a controversial topic that could affect the whole family. Do you support them or ask them to reconsider?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to break up with their partner right before a major event in their partner''s life. Do you advise them to wait or support their timing?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to tell your parents about your past mistakes to deflect from their own. Do you confront them or tell your parents first?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering taking a stand on an issue that could cost them their job. Do you support them or advise caution?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to cut contact with you because of your life choices. Do you try to reconcile or respect their decision?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to lie about their qualifications to get into a program they''re not qualified for. Do you support them or advise honesty?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to tell your parents about your financial struggles without your permission. Do you tell them first or ask them to keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning to confront someone who hurt one of you, but it could escalate badly. Do you participate or try to find another solution?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to make a decision that goes against their spouse''s wishes. Do you support them or encourage compromise?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to tell their ex''s new partner about their ex''s flaws. Do you support them or advise against it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to surprise your parents with news that you know will upset them. Do you warn your parents or let the surprise happen?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering ending a long-term friendship over a minor disagreement. Do you encourage reconciliation or support their decision?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to reveal a secret about another family member at a family gathering. Do you try to stop them or let it happen?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to make a major life change without consulting anyone who cares about them. Do you offer advice or respect their independence?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling wants to borrow a significant amount of money from you but has a history of not paying back loans. Do you lend it or refuse?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend group is planning to do something that could get you all in serious trouble. Do you participate to maintain friendships or opt out?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member is planning to make a public accusation against someone without solid proof. Do you support them or advise caution?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend wants to reconnect with a toxic family member who hurt them in the past. Do you support them or express concerns?', NOW()),
('DILEMMA', 'Family & Friends', 'Your sibling is planning to tell your parents about your secret hobby that they disapprove of. Do you tell them first or ask your sibling to keep quiet?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is considering taking a job that would require them to compromise their values. Do you support them or advise against it?', NOW()),
('DILEMMA', 'Family & Friends', 'Your family member wants to exclude you from a family event because of a past disagreement. Do you try to reconcile or accept the exclusion?', NOW()),
('DILEMMA', 'Family & Friends', 'Your friend is planning to end their relationship in a way that would publicly humiliate their partner. Do you support them or advise a different approach?', NOW());
