-- SQL script to insert 100 questions per category into the content table for Uncover app
-- Note: You may need to temporarily disable RLS or adjust policies in the Supabase dashboard before running this

INSERT INTO content (content, type, category) VALUES

-- Family & Friends Questions
('What''s a family tradition that means a lot to you and why?', 'questions', 'family-friends'),
('How has a friend influenced a major life decision you''ve made?', 'questions', 'family-friends'),
('What''s the most memorable family vacation you''ve been on?', 'questions', 'family-friends'),
('Who''s the family member you turn to for advice, and why?', 'questions', 'family-friends'),
('What''s a funny story about a family gathering that still makes you laugh?', 'questions', 'family-friends'),
('How do you stay connected with friends who live far away?', 'questions', 'family-friends'),
('What''s a lesson about friendship you learned the hard way?', 'questions', 'family-friends'),
('What''s a small gesture from a family member that made a big impact on you?', 'questions', 'family-friends'),
('How do you handle disagreements with close friends?', 'questions', 'family-friends'),
('What''s a childhood memory with a sibling or cousin that shaped who you are?', 'questions', 'family-friends'),
('What''s the kindest thing a friend has ever done for you?', 'questions', 'family-friends'),
('How do you celebrate special occasions with your family?', 'questions', 'family-friends'),
('What''s a family recipe or meal that brings back memories?', 'questions', 'family-friends'),
('Who in your family do you admire most, and why?', 'questions', 'family-friends'),
('What''s a time a friend helped you through a tough situation?', 'questions', 'family-friends'),
('How has your relationship with your parents evolved over time?', 'questions', 'family-friends'),
('What''s the best advice a friend has ever given you?', 'questions', 'family-friends'),
('What''s a family story or legend that gets told over and over?', 'questions', 'family-friends'),
('How do you make new friends as an adult?', 'questions', 'family-friends'),
('What''s a memory of a grandparent that you hold dear?', 'questions', 'family-friends'),
('What''s a time you felt really supported by your family?', 'questions', 'family-friends'),
('How do you keep in touch with family members who live far away?', 'questions', 'family-friends'),
('What''s a funny nickname or inside joke in your family?', 'questions', 'family-friends'),
('What''s the most adventurous thing you''ve done with a friend?', 'questions', 'family-friends'),
('How do you show appreciation for your family?', 'questions', 'family-friends'),
('What''s a time a friend surprised you with their kindness?', 'questions', 'family-friends'),
('What''s a family holiday tradition you look forward to each year?', 'questions', 'family-friends'),
('How do you handle it when a friend lets you down?', 'questions', 'family-friends'),
('What''s a memory of a family pet that makes you smile?', 'questions', 'family-friends'),
('What''s the most meaningful conversation you''ve had with a friend?', 'questions', 'family-friends'),
('How has a family member inspired you to be a better person?', 'questions', 'family-friends'),
('What''s a time you and a friend overcame a challenge together?', 'questions', 'family-friends'),
('What''s a family value or belief that you hold close to your heart?', 'questions', 'family-friends'),
('How do you make time for friends despite a busy schedule?', 'questions', 'family-friends'),
('What''s a memory of a family reunion that stands out to you?', 'questions', 'family-friends'),
('What''s the longest friendship you''ve had, and how did it start?', 'questions', 'family-friends'),
('How do you support a family member going through a tough time?', 'questions', 'family-friends'),
('What''s a spontaneous adventure you''ve had with friends?', 'questions', 'family-friends'),
('What''s a family heirloom or object that means a lot to you?', 'questions', 'family-friends'),
('How do you rebuild trust with a friend after a disagreement?', 'questions', 'family-friends'),
('What''s a time your family came together to help someone in need?', 'questions', 'family-friends'),
('What''s a friend''s quirk or habit that you find endearing?', 'questions', 'family-friends'),
('How do you honor the memory of a family member who has passed?', 'questions', 'family-friends'),
('What''s a time a friend made you feel truly understood?', 'questions', 'family-friends'),
('What''s a family trip or outing that didn''t go as planned but was still fun?', 'questions', 'family-friends'),
('How do you stay patient with friends who have different views?', 'questions', 'family-friends'),
('What''s a family game or activity that always brings everyone together?', 'questions', 'family-friends'),
('What''s a time a friend encouraged you to step out of your comfort zone?', 'questions', 'family-friends'),
('How do you show gratitude to your family for their support?', 'questions', 'family-friends'),
('What''s a memory of a friend''s celebration that you loved being part of?', 'questions', 'family-friends'),
('What''s a family challenge or hardship that made you stronger?', 'questions', 'family-friends'),
('How do you help a friend who''s feeling overwhelmed?', 'questions', 'family-friends'),
('What''s a family photo or memento that brings back happy memories?', 'questions', 'family-friends'),
('What''s a time a friend taught you something new and valuable?', 'questions', 'family-friends'),
('How do you balance time between family and friends?', 'questions', 'family-friends'),
('What''s a funny or embarrassing moment you shared with a friend?', 'questions', 'family-friends'),
('What''s a family member''s talent or skill that amazes you?', 'questions', 'family-friends'),
('How do you make amends with a friend after a misunderstanding?', 'questions', 'family-friends'),
('What''s a time your family supported a dream or goal of yours?', 'questions', 'family-friends'),
('What''s a friend''s achievement that you''re incredibly proud of?', 'questions', 'family-friends'),
('How do you create special moments with your family?', 'questions', 'family-friends'),
('What''s a time a friend helped you see a situation in a new way?', 'questions', 'family-friends'),
('What''s a family saying or motto that you live by?', 'questions', 'family-friends'),
('How do you celebrate a friend''s success or good news?', 'questions', 'family-friends'),
('What''s a memory of helping a family member with something important?', 'questions', 'family-friends'),
('What''s a time a friend made a tough day much better?', 'questions', 'family-friends'),
('How do you keep family traditions alive with younger generations?', 'questions', 'family-friends'),
('What''s a shared interest or hobby you have with a close friend?', 'questions', 'family-friends'),
('What''s a time a family member showed incredible strength or resilience?', 'questions', 'family-friends'),
('How do you support a friend who''s going through a big change?', 'questions', 'family-friends'),
('What''s a family memory that always brings a smile to your face?', 'questions', 'family-friends'),
('What''s a time a friend stood up for you when you needed it?', 'questions', 'family-friends'),
('How do you show your family you care in small, everyday ways?', 'questions', 'family-friends'),
('What''s a memory of a road trip or adventure with friends?', 'questions', 'family-friends'),
('What''s a family member''s story of courage that inspires you?', 'questions', 'family-friends'),
('How do you make a new friend feel welcomed and included?', 'questions', 'family-friends'),
('What''s a time your family worked together to solve a problem?', 'questions', 'family-friends'),
('What''s a friend''s gesture or gift that touched your heart?', 'questions', 'family-friends'),
('How do you stay close to family despite busy schedules?', 'questions', 'family-friends'),
('What''s a time a friend shared a life-changing idea with you?', 'questions', 'family-friends'),
('What''s a family event or milestone you''ll never forget?', 'questions', 'family-friends'),
('How do you keep a friendship strong over many years?', 'questions', 'family-friends'),
('What''s a family lesson about kindness that stuck with you?', 'questions', 'family-friends'),
('What''s a time a friend made you laugh until you cried?', 'questions', 'family-friends'),
('How do you help family members feel appreciated and valued?', 'questions', 'family-friends'),
('What''s a memory of a friend''s party or event that was unforgettable?', 'questions', 'family-friends'),
('What''s a family tradition you''d like to start or continue?', 'questions', 'family-friends'),
('How do you reconnect with a friend after a long time apart?', 'questions', 'family-friends'),
('What''s a time a family member helped you overcome a fear?', 'questions', 'family-friends'),
('What''s a friend''s personality trait that you admire most?', 'questions', 'family-friends'),
('How do you make family gatherings more fun or meaningful?', 'questions', 'family-friends'),
('What''s a time a friend supported you during a personal struggle?', 'questions', 'family-friends'),
('What''s a family memory tied to a specific place or home?', 'questions', 'family-friends'),
('How do you show a friend you''re there for them no matter what?', 'questions', 'family-friends'),
('What''s a family achievement or success you''re proud to be part of?', 'questions', 'family-friends'),
('What''s a time a friend surprised you with their thoughtfulness?', 'questions', 'family-friends'),
('How do you teach younger family members about your values?', 'questions', 'family-friends'),
('What''s a memory of a friend''s kindness that still warms your heart?', 'questions', 'family-friends'),
('What''s a family bond or connection that means the world to you?', 'questions', 'family-friends'),

-- Dating & Relationship Questions
('What''s the most romantic gesture you''ve ever made or received?', 'questions', 'dating-relationship'),
('How do you know when you''ve found ''the one''?', 'questions', 'dating-relationship'),
('What''s a relationship lesson you wish you learned earlier?', 'questions', 'dating-relationship'),
('What''s the most important quality you look for in a partner?', 'questions', 'dating-relationship'),
('How do you keep the spark alive in a long-term relationship?', 'questions', 'dating-relationship'),
('What''s a memorable first date story you have?', 'questions', 'dating-relationship'),
('How do you handle differences in communication styles with a partner?', 'questions', 'dating-relationship'),
('What''s something small your partner does that makes you feel loved?', 'questions', 'dating-relationship'),
('How do you balance personal space and togetherness in a relationship?', 'questions', 'dating-relationship'),
('What''s a relationship goal you''re currently working toward?', 'questions', 'dating-relationship'),
('What''s the sweetest thing someone has said to you on a date?', 'questions', 'dating-relationship'),
('How do you show your partner you appreciate them every day?', 'questions', 'dating-relationship'),
('What''s a romantic destination you''d love to visit with a partner?', 'questions', 'dating-relationship'),
('How do you navigate tough conversations in a relationship?', 'questions', 'dating-relationship'),
('What''s a time a partner supported you in a way that meant a lot?', 'questions', 'dating-relationship'),
('How do you handle jealousy or insecurity in a relationship?', 'questions', 'dating-relationship'),
('What''s a romantic memory that still makes your heart flutter?', 'questions', 'dating-relationship'),
('How do you know if a relationship is worth fighting for?', 'questions', 'dating-relationship'),
('What''s a gesture or gift from a partner that touched you deeply?', 'questions', 'dating-relationship'),
('How do you build trust with someone you''re dating?', 'questions', 'dating-relationship'),
('What''s a time you learned something new about love from a partner?', 'questions', 'dating-relationship'),
('How do you make time for romance amidst a busy life?', 'questions', 'dating-relationship'),
('What''s a relationship challenge you''ve overcome and grown from?', 'questions', 'dating-relationship'),
('How do you express love in ways that aren''t just words?', 'questions', 'dating-relationship'),
('What''s a dating experience that taught you an important lesson?', 'questions', 'dating-relationship'),
('How do you handle different expectations about the future with a partner?', 'questions', 'dating-relationship'),
('What''s a small act of kindness from a partner that made your day?', 'questions', 'dating-relationship'),
('How do you keep dating fun and exciting over time?', 'questions', 'dating-relationship'),
('What''s a time a partner helped you see yourself in a better light?', 'questions', 'dating-relationship'),
('How do you decide when to take a relationship to the next level?', 'questions', 'dating-relationship'),
('What''s a romantic tradition you''d like to start with someone?', 'questions', 'dating-relationship'),
('How do you support a partner during their toughest moments?', 'questions', 'dating-relationship'),
('What''s a dating story that still makes you laugh?', 'questions', 'dating-relationship'),
('How do you handle it when a partner needs space or time alone?', 'questions', 'dating-relationship'),
('What''s a moment in a relationship that made you feel truly connected?', 'questions', 'dating-relationship'),
('How do you communicate your needs without feeling vulnerable?', 'questions', 'dating-relationship'),
('What''s a time a partner surprised you with something thoughtful?', 'questions', 'dating-relationship'),
('How do you handle disagreements about money in a relationship?', 'questions', 'dating-relationship'),
('What''s a dating tip or piece of advice that really worked for you?', 'questions', 'dating-relationship'),
('How do you rebuild connection after a period of distance?', 'questions', 'dating-relationship'),
('What''s a romantic song or movie that means a lot to you?', 'questions', 'dating-relationship'),
('How do you show a partner they can rely on you?', 'questions', 'dating-relationship'),
('What''s a time a relationship taught you about forgiveness?', 'questions', 'dating-relationship'),
('How do you make a partner feel special on an ordinary day?', 'questions', 'dating-relationship'),
('What''s a dating mistake you made that you now see as a blessing?', 'questions', 'dating-relationship'),
('How do you handle different love languages in a relationship?', 'questions', 'dating-relationship'),
('What''s a memory of a partner''s laugh or smile that stays with you?', 'questions', 'dating-relationship'),
('How do you plan surprises or special moments for a partner?', 'questions', 'dating-relationship'),
('What''s a time a partner stood by you when you needed them most?', 'questions', 'dating-relationship'),
('How do you keep honesty at the core of your relationship?', 'questions', 'dating-relationship'),
('What''s a romantic dream or fantasy you''d love to share with someone?', 'questions', 'dating-relationship'),
('How do you handle it when a partner''s family or friends don''t approve?', 'questions', 'dating-relationship'),
('What''s a time a small gesture from a partner meant everything to you?', 'questions', 'dating-relationship'),
('How do you maintain your own identity while in a relationship?', 'questions', 'dating-relationship'),
('What''s a dating adventure or trip you''ll never forget?', 'questions', 'dating-relationship'),
('How do you encourage a partner to pursue their dreams?', 'questions', 'dating-relationship'),
('What''s a time a partner helped you through a personal crisis?', 'questions', 'dating-relationship'),
('How do you handle long-distance challenges in a relationship?', 'questions', 'dating-relationship'),
('What''s a romantic idea or date you''d love to try?', 'questions', 'dating-relationship'),
('How do you show patience when a partner is going through a rough patch?', 'questions', 'dating-relationship'),
('What''s a time a partner''s words gave you strength or hope?', 'questions', 'dating-relationship'),
('How do you create a safe space for vulnerability in a relationship?', 'questions', 'dating-relationship'),
('What''s a dating memory that taught you about true connection?', 'questions', 'dating-relationship'),
('How do you handle differences in lifestyle or habits with a partner?', 'questions', 'dating-relationship'),
('What''s a time a partner made you feel truly cherished?', 'questions', 'dating-relationship'),
('How do you celebrate anniversaries or milestones with a partner?', 'questions', 'dating-relationship'),
('What''s a relationship book or resource that helped you grow?', 'questions', 'dating-relationship'),
('How do you handle it when a partner''s past affects your present?', 'questions', 'dating-relationship'),
('What''s a time a partner''s support made a dream come true?', 'questions', 'dating-relationship'),
('How do you keep communication open and honest over time?', 'questions', 'dating-relationship'),
('What''s a romantic place or moment that felt like a movie scene?', 'questions', 'dating-relationship'),
('How do you help a partner feel confident and valued?', 'questions', 'dating-relationship'),
('What''s a time a relationship showed you the power of teamwork?', 'questions', 'dating-relationship'),
('How do you handle stress or external pressures as a couple?', 'questions', 'dating-relationship'),
('What''s a dating experience that made you believe in love again?', 'questions', 'dating-relationship'),
('How do you make every day with a partner feel meaningful?', 'questions', 'dating-relationship'),
('What''s a time a partner''s action spoke louder than words?', 'questions', 'dating-relationship'),
('How do you handle different priorities or goals in a relationship?', 'questions', 'dating-relationship'),
('What''s a memory of a partner''s kindness that melted your heart?', 'questions', 'dating-relationship'),
('How do you create shared memories or traditions with a partner?', 'questions', 'dating-relationship'),
('What''s a time a relationship taught you about patience?', 'questions', 'dating-relationship'),
('How do you support a partner''s hobbies or passions?', 'questions', 'dating-relationship'),
('What''s a dating moment that made you feel truly alive?', 'questions', 'dating-relationship'),
('How do you handle misunderstandings before they become bigger issues?', 'questions', 'dating-relationship'),
('What''s a time a partner made a sacrifice for your happiness?', 'questions', 'dating-relationship'),
('How do you keep growing individually while growing as a couple?', 'questions', 'dating-relationship'),
('What''s a romantic quote or saying that resonates with you?', 'questions', 'dating-relationship'),
('How do you show a partner you''re committed for the long haul?', 'questions', 'dating-relationship'),
('What''s a time a relationship helped you heal from past pain?', 'questions', 'dating-relationship'),
('How do you handle tough decisions as a team with a partner?', 'questions', 'dating-relationship'),
('What''s a dating memory that still gives you butterflies?', 'questions', 'dating-relationship'),
('How do you make a partner feel safe to share their deepest thoughts?', 'questions', 'dating-relationship'),
('What''s a time a partner''s belief in you pushed you to succeed?', 'questions', 'dating-relationship'),
('How do you keep a relationship fresh after many years?', 'questions', 'dating-relationship'),
('What''s a romantic plan or dream you have for the future?', 'questions', 'dating-relationship'),
('How do you show love through actions rather than words?', 'questions', 'dating-relationship'),
('What''s a time a relationship made you a better version of yourself?', 'questions', 'dating-relationship'),
('How do you handle change or uncertainty with a partner by your side?', 'questions', 'dating-relationship'),
('What''s a memory of a partner''s touch or presence that comforted you?', 'questions', 'dating-relationship'),

-- Note: Due to the token limit, this file currently includes only the first 100 questions for 'family-friends' and 'dating-relationship'. The full script with all 100 questions for each of the remaining categories (fiction, only-wrong-answers, travel, money, 18+, randomized) will be provided in subsequent updates or can be generated based on the pattern shown.

-- To execute this script, copy and paste it into the Supabase SQL Editor in your dashboard. If you encounter RLS issues, you may need to temporarily disable RLS or adjust the policy as an admin before running this insert.
