-- SQL script to add 100 more content items (questions, situations, dilemmas) per category
-- Focusing on remaining categories: dating-relationship, fiction, only-wrong-answers, travel, money, 18+, randomized
-- Disable RLS temporarily for insertion
ALTER TABLE content DISABLE ROW LEVEL SECURITY;

-- Dating-Relationship Category (100 additional)
INSERT INTO content (content, type, category) VALUES
('What''s the most surprising thing you''ve learned about love through experience?', 'questions', 'dating-relationship'),
('Your partner wants to try something new in your relationship that makes you uncomfortable. How do you approach this conversation?', 'situations', 'dating-relationship'),
('Would you rather have a partner who challenges you intellectually or one who comforts you emotionally?', 'dilemmas', 'dating-relationship'),
('How do you maintain your sense of self while deeply committed to a relationship?', 'questions', 'dating-relationship'),
('You notice your partner seems distant but claims nothing''s wrong. Do you push for answers or give them space?', 'situations', 'dating-relationship'),
('Is it more important to share core values or interests with a partner?', 'dilemmas', 'dating-relationship'),
('What''s a relationship lesson that completely changed your approach to love?', 'questions', 'dating-relationship'),
('Your partner receives a dream job offer in another country. How do you navigate this decision together?', 'situations', 'dating-relationship'),
('Would you rather have passionate arguments with make-up moments or complete harmony with little conflict?', 'dilemmas', 'dating-relationship'),
('How do you rebuild intimacy after a period of emotional distance in a relationship?', 'questions', 'dating-relationship'),
('You discover your partner has a completely different political view. How do you handle this long-term?', 'situations', 'dating-relationship'),
('Is it better to work through relationship problems immediately or take time to reflect before discussing?', 'dilemmas', 'dating-relationship'),
('What''s the most meaningful way a partner has shown they understand you?', 'questions', 'dating-relationship'),
('Your partner forgets an important anniversary. How do you express your feelings without making them defensive?', 'situations', 'dating-relationship'),
('Would you rather have a partner who plans everything or one who''s spontaneous?', 'dilemmas', 'dating-relationship'),
('How do you nurture emotional safety in a relationship?', 'questions', 'dating-relationship'),
('Your partner''s family doesn''t approve of your relationship. How do you handle gatherings and interactions?', 'situations', 'dating-relationship'),
('Is it more important to feel understood by your partner or to understand them?', 'dilemmas', 'dating-relationship'),
('What''s a small daily habit that strengthens your relationship?', 'questions', 'dating-relationship'),
('You and your partner have very different approaches to finances. How do you find common ground?', 'situations', 'dating-relationship'),
('Would you rather have a partner who shares your hobbies or introduces you to new ones?', 'dilemmas', 'dating-relationship'),
('How do you maintain passion in a long-term relationship without falling into routine?', 'questions', 'dating-relationship'),
('Your partner wants to move in together but you''re not ready. How do you communicate this?', 'situations', 'dating-relationship'),
('Is it better to discuss relationship issues as they arise or have scheduled check-ins?', 'dilemmas', 'dating-relationship'),
('What''s the most important quality for weathering tough times in a relationship?', 'questions', 'dating-relationship'),
('Your partner is offered their dream job that requires extensive travel. How do you support them while maintaining your connection?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s your best friend or one who brings out new aspects of your personality?', 'dilemmas', 'dating-relationship'),
('How do you balance independence with togetherness in a healthy relationship?', 'questions', 'dating-relationship'),
('You''re attracted to someone outside your relationship. How do you process and handle these feelings?', 'situations', 'dating-relationship'),
('Is it more important to feel completely comfortable with a partner or to feel they help you grow?', 'dilemmas', 'dating-relationship'),
('What''s a relationship milestone that surprised you by its emotional significance?', 'questions', 'dating-relationship'),
('Your partner wants to start a family but you''re unsure. How do you navigate this fundamental difference?', 'situations', 'dating-relationship'),
('Would you rather have a partner who remembers every detail about you or one who surprises you with grand gestures?', 'dilemmas', 'dating-relationship'),
('How do you maintain trust after it''s been broken in a relationship?', 'questions', 'dating-relationship'),
('Your partner is going through depression. How do you support them without losing yourself?', 'situations', 'dating-relationship'),
('Is it better to have similar conflict resolution styles or complementary ones?', 'dilemmas', 'dating-relationship'),
('What''s the most important lesson you''ve learned about communication in relationships?', 'questions', 'dating-relationship'),
('You discover your partner lied about something significant. How do you approach rebuilding trust?', 'situations', 'dating-relationship'),
('Would you rather have a relationship where you never fight or one where conflicts lead to deeper understanding?', 'dilemmas', 'dating-relationship'),
('How do you know when you''re ready to fully commit to someone?', 'questions', 'dating-relationship'),
('Your partner wants to get married but you''re content as you are. How do you have this conversation?', 'situations', 'dating-relationship'),
('Is it more important to share life goals with a partner or to have similar daily habits?', 'dilemmas', 'dating-relationship'),
('What''s a relationship ritual that keeps you connected during busy times?', 'questions', 'dating-relationship'),
('Your partner''s career suddenly takes off while yours stalls. How do you manage potential resentment?', 'situations', 'dating-relationship'),
('Would you rather have a partner who plans romantic dates or one who shows love through daily acts?', 'dilemmas', 'dating-relationship'),
('How do you maintain individuality while building a shared life with someone?', 'questions', 'dating-relationship'),
('Your partner wants to relocate for their career but you''d be leaving your support network. How do you decide?', 'situations', 'dating-relationship'),
('Is it better to have a partner who shares your worldview or challenges it?', 'dilemmas', 'dating-relationship'),
('What''s the most important quality for sustaining long-term attraction?', 'questions', 'dating-relationship'),
('You''re considering an open relationship but have reservations. How do you explore this safely?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely reliable or one who''s excitingly unpredictable?', 'dilemmas', 'dating-relationship'),
('How do you rebuild a relationship after a period of separation?', 'questions', 'dating-relationship'),
('Your partner''s past relationships keep coming up in arguments. How do you move forward?', 'situations', 'dating-relationship'),
('Is it more important to feel secure in a relationship or to feel deeply passionate?', 'dilemmas', 'dating-relationship'),
('What''s a small gesture that makes you feel truly loved?', 'questions', 'dating-relationship'),
('Your partner wants to combine finances but you value financial independence. How do you compromise?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s your social equal or one who introduces you to new circles?', 'dilemmas', 'dating-relationship'),
('How do you maintain emotional connection during physical separation?', 'questions', 'dating-relationship'),
('Your partner wants to try couple''s therapy as a preventative measure. How do you respond?', 'situations', 'dating-relationship'),
('Is it better to share all your thoughts with a partner or maintain some privacy?', 'dilemmas', 'dating-relationship'),
('What''s the most surprising benefit you''ve experienced from being in a committed relationship?', 'questions', 'dating-relationship'),
('Your partner''s family expects you to participate in traditions that conflict with your values. How do you handle this?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely ambitious or one who prioritizes work-life balance?', 'dilemmas', 'dating-relationship'),
('How do you know when you''ve found someone truly compatible for the long term?', 'questions', 'dating-relationship'),
('You''re considering ending the relationship but aren''t completely sure. How do you evaluate this decision?', 'situations', 'dating-relationship'),
('Is it more important to have physical chemistry or emotional intimacy in a relationship?', 'dilemmas', 'dating-relationship'),
('What''s the most important relationship skill that isn''t often discussed?', 'questions', 'dating-relationship'),
('Your partner wants to take a break from the relationship. How do you approach this period?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely organized or one who''s creatively spontaneous?', 'dilemmas', 'dating-relationship'),
('How do you maintain romance after years together?', 'questions', 'dating-relationship'),
('Your partner''s past trauma affects your relationship. How do you support them while protecting your own emotional health?', 'situations', 'dating-relationship'),
('Is it better to have a partner who shares your taste in music/art or one who introduces you to new cultural experiences?', 'dilemmas', 'dating-relationship'),
('What''s a relationship challenge that ultimately brought you closer?', 'questions', 'dating-relationship'),
('You''re considering moving in together but have different living styles. How do you prepare?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely affectionate in private or moderately affectionate in public?', 'dilemmas', 'dating-relationship'),
('How do you handle fundamental differences in religious or spiritual beliefs?', 'questions', 'dating-relationship'),
('Your partner wants to take a year off to travel but you prefer stability. How do you find middle ground?', 'situations', 'dating-relationship'),
('Is it more important to have similar energy levels or complementary ones in a relationship?', 'dilemmas', 'dating-relationship'),
('What''s the most surprising way your partner has influenced your personal growth?', 'questions', 'dating-relationship'),
('Your partner''s career requires frequent relocations. How do you maintain your own career aspirations?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely patient or one who pushes you out of your comfort zone?', 'dilemmas', 'dating-relationship'),
('How do you maintain sexual intimacy during stressful periods?', 'questions', 'dating-relationship'),
('You discover your partner has been keeping a significant secret. How do you approach rebuilding trust?', 'situations', 'dating-relationship'),
('Is it better to have a partner who shares your political views or one who challenges them?', 'dilemmas', 'dating-relationship'),
('What''s the most important lesson you''ve learned about compromise in relationships?', 'questions', 'dating-relationship'),
('Your partner wants to start a business together but you''re concerned about mixing love and work. How do you evaluate this?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely tidy or one who''s creatively messy?', 'dilemmas', 'dating-relationship'),
('How do you handle differences in libido in a long-term relationship?', 'questions', 'dating-relationship'),
('Your partner receives bad news and withdraws emotionally. How do you offer support?', 'situations', 'dating-relationship'),
('Is it more important to have similar senses of humor or similar values?', 'dilemmas', 'dating-relationship'),
('What''s a relationship tradition that helps you stay connected?', 'questions', 'dating-relationship'),
('You''re considering having children but your partner is unsure. How do you navigate this conversation?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely punctual or one who''s flexible with time?', 'dilemmas', 'dating-relationship'),
('How do you maintain individuality in a deeply committed relationship?', 'questions', 'dating-relationship'),
('Your partner wants to adopt a lifestyle change (veganism, minimalism, etc.) that affects you both. How do you approach this?', 'situations', 'dating-relationship'),
('Is it better to have a partner who''s extremely social or one who prefers quiet time together?', 'dilemmas', 'dating-relationship'),
('What''s the most important quality for navigating life''s unexpected challenges as a couple?', 'questions', 'dating-relationship'),
('Your partner wants to take a sabbatical from work but finances are tight. How do you approach this decision?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely close with their family or more independent?', 'dilemmas', 'dating-relationship'),
('How do you handle disagreements about parenting styles before having children?', 'questions', 'dating-relationship'),
('Your partner''s best friend doesn''t like you. How do you handle this dynamic?', 'situations', 'dating-relationship'),
('Is it more important to have similar sleep schedules or compatible morning/night routines?', 'dilemmas', 'dating-relationship'),
('What''s the most surprising benefit of being with someone different from you?', 'questions', 'dating-relationship'),
('You''re offered a dream job in another city but your partner can''t relocate. How do you decide?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely health-conscious or one who indulges with you?', 'dilemmas', 'dating-relationship'),
('How do you maintain emotional connection during periods of physical separation?', 'questions', 'dating-relationship'),
('Your partner wants to try therapy but you''re skeptical. How do you approach this?', 'situations', 'dating-relationship'),
('Is it better to have a partner who shares your taste in decor or one who brings new aesthetic perspectives?', 'dilemmas', 'dating-relationship'),
('What''s the most important lesson you''ve learned about maintaining passion in a long-term relationship?', 'questions', 'dating-relationship'),
('Your partner wants to take a break from social media but you enjoy sharing your life online. How do you navigate this?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely frugal or one who enjoys spending on experiences?', 'dilemmas', 'dating-relationship'),
('How do you handle differences in social needs in a relationship?', 'questions', 'dating-relationship'),
('Your partner wants to start a family before you feel financially ready. How do you have this conversation?', 'situations', 'dating-relationship'),
('Is it better to have a partner who plans everything or one who''s spontaneous?', 'dilemmas', 'dating-relationship'),
('What''s the most meaningful way a partner has supported your personal growth?', 'questions', 'dating-relationship'),
('Your partner''s career requires frequent networking events. How do you handle your different social needs?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely affectionate or one who shows love through actions?', 'dilemmas', 'dating-relationship'),
('How do you maintain trust when working through jealousy issues?', 'questions', 'dating-relationship'),
('Your partner wants to combine finances but you value financial independence. How do you find middle ground?', 'situations', 'dating-relationship'),
('Is it better to have a partner who shares your political views or one who challenges them?', 'dilemmas', 'dating-relationship'),
('What''s the most important quality for navigating conflict in a relationship?', 'questions', 'dating-relationship'),
('Your partner wants to try new things in the bedroom that make you uncomfortable. How do you communicate your boundaries?', 'situations', 'dating-relationship'),
('Would you rather have a partner who''s extremely close with their family or more independent?', 'dilemmas', 'dating-relationship'),
('How do you rebuild intimacy after a breach of trust?', 'questions', 'dating-relationship'),
('Your partner wants to start a business together but you''re concerned about mixing love and work. How do you evaluate this?', 'situations', 'dating-relationship'),
('Is it better to have similar conflict resolution styles or complementary ones?', 'dilemmas', 'dating-relationship'),
('What''s the most surprising lesson you''ve learned about love?', 'questions', 'dating-relationship');

-- Note: Due to token limitations, this shows the pattern for one category. Follow-up scripts will cover:
-- fiction, only-wrong-answers, travel, money, 18+, randomized
-- Each with 100 carefully crafted content items per category

-- Re-enable RLS (policy already exists)
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
